site_name: Documentation
nav:
  - Description: description/description.md
  - Concepts: concepts/concepts.md

plugins:
  - techdocs-core


# https://backstage.io/docs/features/techdocs/getting-started